// <auto-generated />
namespace CNBlogs.Apply.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SetApprovedTimenull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetApprovedTimenull));
        
        string IMigrationMetadata.Id
        {
            get { return "201604131417079_Set-ApprovedTime-null"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
